language: ruby
rvm:
  - 2.2.2

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/85894647e12ac6d3b621
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
